apiVersion: v1
kind: Secret
metadata:
  name: banking-db-secret
  namespace: banking
type: Opaque
stringData:
  POSTGRES_USER: banking
  POSTGRES_PASSWORD: bankingpass
  POSTGRES_DB: banking
  # host = IP thật của DB ngoài cluster
  DATABASE_URL: "postgresql://banking:bankingpass@10.1.34.142:5432/banking"
  REDIS_URL: "redis://redis:6379/0"